version: '3.8'
services:
  db:
    image: 'postgres'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - db:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    networks:
      - rest_data_api

  # cache:
  #   image: redis:6.2-alpine
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  #   volumes: 
  #     - cache:/data

  api:
    build: .
    command: py manage.py runserver
    volumes:
      - .:/app
    ports:
      - "80:8000"
    depends_on:
      - db
      # - cache
    environment:
      DB_USER: postgres
      DB_PASSWORD: 123456
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - rest_data_api

volumes:
  db:
    driver: local
networks:
  rest_data_api: