# Generated by Django 4.1.7 on 2023-03-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_autosend',
            field=models.BooleanField(default=False),
        ),
    ]
